ALTER TABLE "Event" ADD COLUMN IF NOT EXISTS "mode" TEXT NOT NULL DEFAULT 'Online';
ALTER TABLE "Course" ADD COLUMN IF NOT EXISTS "discountedPrice" TEXT;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "thumbnail" TEXT;
